/**
 * One definition of what a valid set is, enforced at the client input, the API
 * boundary and the database.
 *
 * These live next to the Drizzle schema on purpose: the bounds below are the
 * column definitions restated in Zod, so a change to `numeric(6, 2)` has an
 * obvious place to land. Nothing here imports the database, so the client can
 * validate against the same rules before it ever hits the network.
 */

import { z } from "zod";

/** `numeric(6, 2)`: four digits before the point, two after. */
export const WEIGHT_MAX = 9999.99;
/** The smallest plate jump anyone loads, and the granularity of the number pad. */
export const WEIGHT_STEP = 0.25;

/** RPE is a 6-to-10 scale with half steps. It is a slider, never a text field. */
export const RPE_MIN = 6;
export const RPE_MAX = 10;
export const RPE_STEP = 0.5;

export const uuid = z.uuid();

/**
 * Weight is always kilograms. `user.unitPref` is a display concern, so a unit
 * mistake can never reach a stored row.
 *
 * Zero is allowed: bodyweight dips, push-ups and band work are real sets, and
 * refusing them would push people into typing a fake 1 kg.
 */
export const weightKg = z
  .number()
  .min(0, "Weight can't be negative.")
  .max(WEIGHT_MAX, "That weight is out of range.")
  .refine((w) => Math.abs(w * 100 - Math.round(w * 100)) < 1e-6, {
    message: "Weight goes to two decimal places.",
  });

export const reps = z
  .number()
  .int("Reps have to be whole.")
  .min(1, "A set is at least one rep.")
  .max(1000, "That rep count is out of range.");

export const rpe = z
  .number()
  .min(RPE_MIN)
  .max(RPE_MAX)
  .refine((v) => Math.abs(v / RPE_STEP - Math.round(v / RPE_STEP)) < 1e-9, {
    message: "RPE moves in half points.",
  });

/**
 * The write payload for one set.
 *
 * `id` is generated by the client as a UUIDv7 and is the idempotency key for
 * the whole write path: the server upserts on it, so a retry after a timeout is
 * a no-op rather than a duplicate set quietly inflating someone's volume.
 *
 * `clientCreatedAt` is what the phone believed the time was. It orders rows
 * correctly when a write lands late, which is the case the id is protecting
 * against in the first place.
 */
export const setInput = z.object({
  id: uuid,
  sessionId: uuid,
  exerciseId: uuid,
  setIndex: z.number().int().min(0).max(500),
  weight: weightKg,
  reps,
  rpe: rpe.nullable(),
  // Required, not defaulted. A payload that forgot to say whether this was a
  // warm-up should be rejected, not quietly counted as working volume.
  isWarmup: z.boolean(),
  clientCreatedAt: z.date(),
});

export type SetInput = z.infer<typeof setInput>;

export const sessionStartInput = z.object({
  id: uuid,
  routineDayId: uuid.nullable(),
  notes: z.string().trim().max(2000).nullable(),
});

/** The trailing windows the whole app toggles between. One meaning everywhere. */
export const statWindow = z
  .union([z.literal(7), z.literal(30), z.literal(90)])
  .describe("Trailing window in days.");
