/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as AuthenticatedPlanIndexRouteImport } from './routes/_authenticated/plan/index'
import { Route as AuthenticatedPlanRoutineIdRouteImport } from './routes/_authenticated/plan/$routineId'
import { Route as AuthenticatedTrainIndexRouteImport } from './routes/_authenticated/train/index'
import { Route as AuthenticatedTrainSessionIdRouteImport } from './routes/_authenticated/train/$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanIndexRoute = AuthenticatedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoutineIdRoute =
  AuthenticatedPlanRoutineIdRouteImport.update({
    id: '/plan/$routineId',
    path: '/plan/$routineId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainIndexRoute = AuthenticatedTrainIndexRouteImport.update({
  id: '/train/',
  path: '/train/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainSessionIdRoute =
  AuthenticatedTrainSessionIdRouteImport.update({
    id: '/train/$sessionId',
    path: '/train/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/export': typeof ApiExportRoute
  '/plan/$routineId': typeof AuthenticatedPlanRoutineIdRoute
  '/train/$sessionId': typeof AuthenticatedTrainSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/plan/': typeof AuthenticatedPlanIndexRoute
  '/train/': typeof AuthenticatedTrainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/export': typeof ApiExportRoute
  '/plan/$routineId': typeof AuthenticatedPlanRoutineIdRoute
  '/train/$sessionId': typeof AuthenticatedTrainSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/train': typeof AuthenticatedTrainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/export': typeof ApiExportRoute
  '/_authenticated/plan/$routineId': typeof AuthenticatedPlanRoutineIdRoute
  '/_authenticated/train/$sessionId': typeof AuthenticatedTrainSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_authenticated/plan/': typeof AuthenticatedPlanIndexRoute
  '/_authenticated/train/': typeof AuthenticatedTrainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/progress'
    | '/settings'
    | '/api/export'
    | '/plan/$routineId'
    | '/train/$sessionId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/plan/'
    | '/train/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/progress'
    | '/settings'
    | '/api/export'
    | '/plan/$routineId'
    | '/train/$sessionId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/plan'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/api/export'
    | '/_authenticated/plan/$routineId'
    | '/_authenticated/train/$sessionId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_authenticated/plan/'
    | '/_authenticated/train/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiExportRoute: typeof ApiExportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan/': {
      id: '/_authenticated/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthenticatedPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan/$routineId': {
      id: '/_authenticated/plan/$routineId'
      path: '/plan/$routineId'
      fullPath: '/plan/$routineId'
      preLoaderRoute: typeof AuthenticatedPlanRoutineIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/train/': {
      id: '/_authenticated/train/'
      path: '/train'
      fullPath: '/train/'
      preLoaderRoute: typeof AuthenticatedTrainIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/train/$sessionId': {
      id: '/_authenticated/train/$sessionId'
      path: '/train/$sessionId'
      fullPath: '/train/$sessionId'
      preLoaderRoute: typeof AuthenticatedTrainSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPlanRoutineIdRoute: typeof AuthenticatedPlanRoutineIdRoute
  AuthenticatedTrainSessionIdRoute: typeof AuthenticatedTrainSessionIdRoute
  AuthenticatedPlanIndexRoute: typeof AuthenticatedPlanIndexRoute
  AuthenticatedTrainIndexRoute: typeof AuthenticatedTrainIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPlanRoutineIdRoute: AuthenticatedPlanRoutineIdRoute,
  AuthenticatedTrainSessionIdRoute: AuthenticatedTrainSessionIdRoute,
  AuthenticatedPlanIndexRoute: AuthenticatedPlanIndexRoute,
  AuthenticatedTrainIndexRoute: AuthenticatedTrainIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiExportRoute: ApiExportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
